### ISSUE TITLE
EmailAdress Atribute.

### ISSUE THREAD

**Issue by eliasribeiro** [ryanhorath/PortableDataAnnotations#5]
Tested in Xamarin Platform. EmailAddressAttribute with ErrorMessageResourceName and ErrorMessageResourceType show Exception: System.InvalidOperationException: Either ErrorMessageString or ErrorMessageResourceName must be set, but not both.

Code of sample:
[EmailAddress(ErrorMessageResourceName = "MSG_E01", ErrorMessageResourceType = typeof(Lang.Mensagem))]

Obs.: Required worked.

**Comment by eliasribeiro** [comment]
Alternative than work: [EmailAddress( ErrorMessage = null, ErrorMessageResourceName = "MSG_E02", ErrorMessageResourceType = typeof(Lang.Mensagem))]

**Comment by ryanhorath** [comment]
This project is no longer maintained due to lack of time and because .NET Core has addressed the issues this package targeted. Feel free to fork the code and make any fixes you need.
